### PR TITLE
Update bundler.ts

### PR DESCRIPTION
**Pull request by michael-spengler**
Hi Snel Team.

Thank you for doing what you do. We are great fans of snel!! 

Due to the fact that the base bundler module seems abandoned this was the best workaround / replacement we could come up with.

Thanks to ntrotner this will work - see also: https://github.com/crewdevio/Snel/issues/49#issuecomment-1040461915

Kind regards
Michael & Friends

### CODE REVIEW

**Comment by buttercubz** [comment]
hello @michael-spengler , we are glad that you can take advantage of snel, for my part now I have less time to dedicate to open source, but I would be happy to invite you and give you access to the snel repo to continue supporting

**Comment by buttercubz** [comment]
In the same way, I think I will take advantage of this week to update snel and other tools that surround it.

**Comment by michael-spengler** [comment]
Hi @buttercubz: Thanks a lot for your trust. I'm looking forward to become a snel "collaborator".

**Comment by buttercubz** [comment]
> Hi @buttercubz: Thanks a lot for your trust. I'm looking forward to become a snel "collaborator".

I sent the invitation

**Comment by buttercubz** [comment]
I'm going to close it in favor of #51

**Pull request closed without merging**
